home/urls.py
from django.urls import path

import home.views as home

app_name = 'home'

urlpatterns = [
    path('', home.home_view, name='index'),
    path('speedruns/', home.speedruns_view, name='speedruns'),
]

oauth/urls.py
from django.urls import path

import oauth.views as oauth

app_name = 'oauth'

urlpatterns = [
    path('', oauth.do_oauth, name='login'),
    path('logout/', oauth.log_out, name='logout'),
    path('callback/', oauth.callback, name='callback'),
]

speedrun_web/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('oauth/', include('oauth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('debug/', include(debug_toolbar.urls))] + urlpatterns

home/models.py
from django.db import models

oauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_verified = models.BooleanField(max_length=80, default=False)
    twitch_id = models.IntegerField(blank=True, default=0)
    logo_url = models.URLField(blank=True, default='')

    def __str__(self):
        return '{} - {}'.format(self.user, self.twitch_id)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Oauth(models.Model):
    client_id = models.CharField(max_length=30, help_text='Twitch Client ID.')
    client_secret = models.CharField(max_length=30, help_text='Twitch Application Secret.')
    redirect_uri = models.URLField(help_text='Redirect URL back to this site.<br> '
                                             'Should contain this URI: /oauth/callback/')
    response_type = models.CharField(max_length=255, help_text='This should almost always be: code')
    grant_type = models.CharField(max_length=255, help_text='This should almost always be: authorization_code')
    scope = models.CharField(max_length=255, help_text='You at least need: user_read')

    def __str__(self):
        return 'Twitch Oauth Settings'

    class Meta:
        verbose_name = 'Oauth'
        verbose_name_plural = 'Oauth'

home/views.py
import logging
from django.conf import settings
from django.shortcuts import render

logger = logging.getLogger('app')
config = settings.CONFIG


def home_view(request):
    # View: /
    return render(request, 'home.html')


def speedruns_view(request):
    # View: /speedruns/
    return render(request, 'speedruns.html')

oauth/views.py
import logging
import requests
import urllib.parse
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect
from django.shortcuts import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_http_methods
from django.conf import settings
from oauth.models import Oauth

logger = logging.getLogger('app')
config = settings.CONFIG


def do_oauth(request):
    """
    # View  /oauth/
    """
    oauth = Oauth.objects.all()[0]
    request.session['login_redirect_url'] = get_next_url(request)
    params = {
        'client_id': oauth.client_id,
        'redirect_uri': oauth.redirect_uri,
        'response_type': oauth.response_type,
        'scope': oauth.scope,
    }
    url_params = urllib.parse.urlencode(params)
    url = 'https://id.twitch.tv/oauth2/authorize?{}'.format(url_params)
    return HttpResponseRedirect(url)


def callback(request):
    """
    # View  /oauth/callback/
    """
    try:
        oauth_code = request.GET['code']
        logger.debug('oauth_code: {}'.format(oauth_code))
        access_token = twitch_token(oauth_code)
        logger.debug('access_token: {}'.format(access_token))
        twitch_profile = get_twitch(access_token)
        logger.debug('twitch_profile: {}'.format(twitch_profile))
        logger.debug(twitch_profile)
        auth = login_user(request, twitch_profile)
        if not auth:
            err_msg = 'Unable to complete login process. Report as a Bug.'
            return HttpResponse(err_msg, content_type='text/plain')
        try:
            next_url = request.session['login_redirect_url']
        except Exception:
            next_url = '/'
        return HttpResponseRedirect(next_url)

    except Exception as error:
        logger.exception(error)
        err_msg = 'Fatal Login Error. Report as Bug: %s' % error
        return HttpResponse(err_msg, content_type='text/plain')


@require_http_methods(['POST'])
def log_out(request):
    """
    View  /oauth/logout/
    """
    next_url = get_next_url(request)
    request.session['login_next_url'] = next_url
    logout(request)
    return redirect(next_url)


def login_user(request, data):
    """
    Login or Create New User
    """
    try:
        user = User.objects.filter(username=data['username']).get()
        user = update_profile(user, data)
        user.save()
        login(request, user)
        return True
    except ObjectDoesNotExist:
        user = User.objects.create_user(data['username'], data['email'])
        user = update_profile(user, data)
        user.save()
        login(request, user)
        return True
    except Exception as error:
        logger.exception(error)
        return False


def twitch_token(code):
    """
    Post OAuth code to Twitch and Return access_token
    """
    oauth = Oauth.objects.all()[0]
    url = 'https://id.twitch.tv/oauth2/token'
    data = {
        'client_id': oauth.client_id,
        'client_secret': oauth.client_secret,
        'grant_type': oauth.grant_type,
        'redirect_uri': oauth.redirect_uri,
        'code': code,
    }
    headers = {'Accept': 'application/json'}
    r = requests.post(url, data=data, headers=headers, timeout=10)
    logger.debug('status_code: {}'.format(r.status_code))
    logger.debug('content: {}'.format(r.content))
    return r.json()['access_token']


def get_twitch(access_token):
    """
    Get Twitch Profile for Authenticated User
    """
    url = 'https://api.twitch.tv/kraken/user'
    headers = {
        'Accept': 'application/vnd.twitchtv.v5+json',
        'Authorization': 'OAuth {}'.format(access_token),
    }
    r = requests.get(url, headers=headers, timeout=10)
    logger.debug('status_code: {}'.format(r.status_code))
    logger.debug('content: {}'.format(r.content))
    twitch_profile = r.json()
    return {
        'username': twitch_profile['name'],
        'first_name': twitch_profile['display_name'],
        'email': twitch_profile['email'],
        'email_verified': twitch_profile['email_verified'],
        'user_id': twitch_profile['_id'],
        'logo_url': twitch_profile['logo'],
    }


def update_profile(user, data):
    """
    Update user_profile from GitHub data
    """
    user.first_name = data['first_name']
    user.email = data['email']
    user.profile.email_verified = data['email_verified']
    user.profile.twitch_id = data['user_id']
    user.profile.logo_url = data['logo_url']
    return user


def get_next_url(request):
    """
    Determine 'next' Parameter
    """
    try:
        next_url = request.GET['next']
    except Exception:
        try:
            next_url = request.POST['next']
        except Exception:
            try:
                next_url = request.session['login_next_url']
            except Exception:
                next_url = '/'
    if not next_url:
        next_url = '/'
    return next_url

templates/home.html
{% extends "main.html" %}
{% block home_active %}active{% endblock %}
{% block title %}Home{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row mt-2">
        <div class="col">
            <h1>Howdy!</h1>
            <p class="lead">Welcome home.</p>
            <p>You need to do the following:</p>
            <ul>
                <li>python manage.py createsuperuser</li>
                <li>python manage.py loaddata site-data.json</li>
                <li>Create an app at twitch <a href="https://dev.twitch.tv/dashboard" target="_blank">developer site</a>.</li>
                <li>Login to django <a href="{% url 'admin:index' %}">admin site</a>.</li>
                <li>Configure the Twitch settings in the Oauth section.</li>
                <li>Log out then <a href="{% url 'oauth:login' %}" class="text-info">log in with Twitch</a>.</li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/main.html
{% load staticfiles %}
{% load home_tags %}

<!doctype html>
<html lang="en">
<head>
	<!-- Required tags for bootstrap -->
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Meta -->
	<meta name="author" content="Shane Rice"/>
	<meta name="title" content="Site Title"/>
	<meta name="description" content="Site Description"/>

	<meta property="og:author" content="Shane Rice">
	<meta property="og:title" content="Site Title">
	<meta property="og:description" content="Site Description">
	<meta property="og:type" content="website">
	<meta property="og:url" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url 'home:index' %}">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'images/logo.png' %}">
	<meta property="og:image:type" content="image/png">

	<title>Site Title - {% block title %}{% endblock %}</title>

	<!-- Media -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

	<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'font-awesome/css/all.min.css' %}" rel="stylesheet">
	<link href="{% static 'main/css/main.css' %}" rel="stylesheet">

	{% block head %}{% endblock %}
</head>
<body>

<!-- Main content -->
<div class="container-fluid">
    {% block heading %}
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mt-2">
            <a class="navbar-brand" href="{% url 'home:index' %}">{{ site_title_short }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
                    aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% block home_active %}{% endblock %}">
                        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                    </li>
                    <li class="nav-item {% block about_active %}{% endblock %}">
                        <a class="nav-link" href="{% url 'home:speedruns' %}">Speed</a>
                    </li>
                </ul>

                {% if not request.user.is_authenticated %}
                    <a href="{% url 'oauth:login' %}?next={{ request.path }}" class="btn btn-outline-info" role="button">
                        Log in with Twitch
                        <i class="fas fa-sign-in-alt"></i></a>
                {% else %}
                    <a href="https://www.twitch.tv/settings/profile" target="_blank" class="text-info mr-3">
                        {% if request.user.first_name %}{{ request.user.first_name }}{% else %}{{ request.user.username }}{% endif %}</a>
                    {% if user.is_staff %}
                        <a href="{% url 'admin:index' %}" class="btn btn-outline-primary mr-1" role="button">
                            Admin
                            <i class="fas fa-rocket"></i></a>
                    {% endif %}
                    <a href="" class="log-out btn btn-outline-info" role="button">
                        Log Out
                        <i class="fas fa-sign-out-alt"></i></a>
                {% endif %}
            </div>
        </nav>
    {% endblock %}

    {% block body %}{% endblock %}

    {% block footer %}{% endblock %}
</div>

{% if request.user.is_authenticated %}
    <form id="log-out" action="{% url 'oauth:logout' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.get_full_path }}">
    </form>
{% endif %}

<!-- JS imported at end to improve page loads -->
<script type="text/javascript" src="{% static 'bootstrap/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'font-awesome/js/all.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

{% block tail %}{% endblock %}

</body>
</html>

templates/speedruns.html
{% extends "main.html" %}
{% block speedrun_active %}active{% endblock %}
{% block title %}Speedruns{% endblock %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Speedruns</h1>
            <p class="lead">Sonic go fast...</p>
        </div>
    </div>
{% endblock %}